### ISSUE TITLE
Correctly next images and links

### ISSUE THREAD

**Issue by gregthompson27** [DrTemperance/DrTemperance.github.io#1]
https://github.com/DrTemperance/DrTemperance.github.io/blob/729c46c504b85ad3a994779df62cc63d13430fd4/index.html#L15-L37

@DrTemperance, one quick thing you can change is the way you've nested these `<li>` tags and `<a>` tags. You want to make sure when nesting elements that the opening and closing tags for one element are completely inside of the other's opening and closing tags. So instead of this:

```html
<a href="index.html"> 
   <li class="active-page"> Home 
</a></li> 
```
you're looking for this:
```html
<a href="index.html"> 
   <li class="active-page"> Home </li>
</a>
```

You'll want to make these changes for all your links in the nav section (which you might also have to change in several of your html files)

**Comment by DrTemperance** [comment]
fixed
